# You should not need to modify this file. Please modify the variables in your .env file instead. The env-template.txt
# file contains an example .env file with default values pre-populated.
version: "2.4"

services:

  pingauthorize:
    image: ${PAZ_SIDEBAND_DEVOPS_REGISTRY}/pingauthorize:${PAZ_SIDEBAND_DEVOPS_TAG}
    container_name: pingauthorize
    environment:
      - SERVER_PROFILE_URL=${PAZ_SIDEBAND_PROFILE_URL:-https://github.com/pingidentity/pdg-sideband-test-environment.git}
      - SERVER_PROFILE_PATH=server-profiles/pingauthorize
      - SERVER_PROFILE_BRANCH=${PAZ_SIDEBAND_PROFILE_BRANCH:-main}
      - PAZ_SIDEBAND_REQUEST_CONTEXT_METHOD=${PAZ_SIDEBAND_REQUEST_CONTEXT_METHOD:-state}
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "${PAZ_SIDEBAND_PAZ_PORT:-7443}:1443"

  pingdataconsole:
    image: ${PAZ_SIDEBAND_DEVOPS_REGISTRY}/pingdataconsole:${PAZ_SIDEBAND_DEVOPS_TAG}
    container_name: pingdataconsole
    ports:
      - "${PAZ_SIDEBAND_CONSOLE_PORT:-5443}:8443"

  pingauthorizepap:
    image: ${PAZ_SIDEBAND_DEVOPS_REGISTRY}/pingauthorizepap:${PAZ_SIDEBAND_DEVOPS_TAG}
    container_name: pingauthorizepap
    environment:
      - SERVER_PROFILE_URL=${PAZ_SIDEBAND_PROFILE_URL:-https://github.com/pingidentity/pdg-sideband-test-environment.git}
      - SERVER_PROFILE_PATH=server-profiles/pingauthorizepap
      - SERVER_PROFILE_BRANCH=${PAZ_SIDEBAND_PROFILE_BRANCH:-main}
      - PING_EXTERNAL_BASE_URL=${PAZ_SIDEBAND_PAP_HOSTNAME}:${PAZ_SIDEBAND_PAP_PORT}
      - HTTPS_PORT=8443
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "${PAZ_SIDEBAND_PAP_PORT:-8443}:1443"

