logging:
  level: INFO
  loggers:
    com.pingidentity.dg: DEBUG
server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080
backend:
  data: hub.json
  bannedUsernames:
  - l33t_haxor
